name: Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.2.3)"
        required: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            icon: "assets/logo.ico"
          - os: macos-latest
            icon: "assets/logo.icns"

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v5

      - name: ðŸ“¦ Set up Python & Install uv
        uses: astral-sh/setup-uv@v7

      - name: ðŸ“¦ Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-build-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-build-

      - name: ðŸ“¦ Install dependencies
        run: |
          uv sync
          uv pip install pyinstaller

      - name: ðŸ”¨ Build Project
        shell: bash
        run: |
          uv run pyinstaller --noconsole \
            --icon "${{ matrix.icon }}" \
            --add-data "RinUI:RinUI" \
            --add-data "assets:assets" \
            --add-data "pages:pages" \
            --paths=. \
            --contents-directory . \
            --name=QuicklyGithub \
            --clean \
            --onedir \
            main.py

      - name: ðŸ“¦ Create archive
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            curl -OLk# https://www.stahlworks.com/dev/zip.exe
            ./zip.exe -r -q "dist/QuicklyGithub-Windows.zip" dist/QuicklyGithub/*
          else
            cd dist && ditto -c -k --sequesterRsrc --keepParent QuicklyGithub.app QuicklyGithub-macOS.zip && cd ..
          fi
          ls -lh dist/

      - name: â˜ï¸ Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: QuicklyGithub-${{ runner.os }}
          path: dist/QuicklyGithub-${{ runner.os }}.zip

  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: â¬‡ï¸ Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist/

      - name: ðŸ§± Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v2

      - name: ðŸ“œ Generate CHANGELOG
        id: changelog
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${{ github.ref_name }}"
          if [ -z "$TAG_NAME" ]; then
            TAG_NAME="${{ github.event.inputs.tag }}"
          fi
          git cliff --latest --tag "$TAG_NAME" --config .git-cliff.toml --github-repo "${{ github.repository }}" --output changelog.md
          # cat changelog.md >> $GITHUB_STEP_SUMMARY >> $GITHUB_OUTPUT

      - name: ðŸš€ Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: RinUI Gallery ${{ github.ref_name || github.event.inputs.tag }}
          tag_name: ${{ github.ref_name || github.event.inputs.tag }}
          body_path: changelog.md
          files: dist/*/QuicklyGithub-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}